### ISSUE TITLE
Add list of ports that need opening for server usage

### ISSUE THREAD

**Issue by hubdotcom** [getcloak/cloak-server-demo#1]
Would be good to know what to allow via firewall / security group

Current list:
22 TCP (ansible)
80 TCP (letsencrypt verification)
443 TCP (OpenVPN)
443 UDP (OpenVPN)
500 UDP (IKEv2)
4500 UDP (IKEv2)

53 TCP/UDP (DNS) - is the server acting as a DNS resolver too?

Any missing?

**Comment by psagers** [comment]
Good idea, thanks. Cloak clients will send DNS requests to the server through the tunnel, but those ports don't need to be open on an external firewall.
